language: generic 
sudo: required
services:
    - docker
    
before_install:
    - docker build -t jparrareig/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true jparrareig/docker-react npm run test -- --coverage
